DocWorks for wix-bookings-rc-v2-backend - 6 changes detected, but 8 issue detected changes: Service wix-bookings-rc-v2-backend.sessions operation deleteSession has changed param name from deleteSessionOptions to options Service wix-bookings-rc-v2-backend.sessions operation deleteSession has changed param options type Service wix-bookings-rc-v2-backend.sessions operation deleteSession param options was removed Service wix-bookings-rc-v2-backend.sessions operation deleteSession.examples[0] has changed body Service wix-bookings-rc-v2-backend.sessions message DeleteSessionRequest_5772496212 was removed Service wix-bookings-rc-v2-backend.sessions has a new message DeleteSessionRequest_5290069407
issues:
Operation eq has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (90))
Operation ne has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (130))
Operation eq has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (28))
Operation ne has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (68))
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_all.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1241
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_multiple_filters.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1241
ERROR: The @snippet tag - file 'corvid-docs/examples/deleteSession.es6' not found. File: com_wix_bookings_schedules_api_v1_Schedules_DeleteSession_deleteSession.js line: 8
ERROR: The @snippet tag - file 'corvid-docs/examples/createResource.es6' not found. File: com_wixpress_bookings_resources_core_api_v1_resource_ResourcesService_Create_createResource.js line: 31