DocWorks for wix-bookings-rc-v2-backend - 4 changes detected, but 8 issue detected changes: Service wix-bookings-rc-v2-backend.resources operation updateResourceSchedule has changed param scheduleInfo type Service wix-bookings-rc-v2-backend.resources operation updateResourceSchedule.examples[0] has changed body Service wix-bookings-rc-v2-backend.resources message Schedule_4563954111 was removed Service wix-bookings-rc-v2-backend.resources has a new message Schedule_2414051789
issues:
Operation eq has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (95))
Operation ne has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (135))
Operation eq has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (97))
Operation ne has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (137))
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_all.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1246
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_multiple_filters.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1246
ERROR: The @snippet tag - file 'corvid-docs/examples/deleteSession.es6' not found. File: com_wix_bookings_schedules_api_v1_Schedules_DeleteSession_deleteSession.js line: 8
ERROR: The @snippet tag - file 'corvid-docs/examples/createResource.es6' not found. File: com_wixpress_bookings_resources_core_api_v1_resource_ResourcesService_Create_createResource.js line: 35