DocWorks for wix-bookings-rc-v2-backend - 14 changes detected, but 8 issue detected changes: Service wix-bookings-rc-v2-backend.bookings operation cancelBooking has a new param options Service wix-bookings-rc-v2-backend.bookings operation cancelBooking.examples[0] has changed body Service wix-bookings-rc-v2-backend.bookings operation cancelBooking.examples[1] has changed body Service wix-bookings-rc-v2-backend.bookings has a new message CancelBookingRequest_7528859822 Service wix-bookings-rc-v2-backend.resources operation createResource has changed param resourceInfo type Service wix-bookings-rc-v2-backend.resources operation createResource has changed return type Service wix-bookings-rc-v2-backend.resources operation createResource.examples[0] has changed body Service wix-bookings-rc-v2-backend.resources message Resource_12959995134 member images has changed type Service wix-bookings-rc-v2-backend.resources message Resource_13052683855 was removed Service wix-bookings-rc-v2-backend.resources has a new message Resource_8796704728 Service wix-bookings-rc-v2-backend.resources has a new message Resource_15083711512 Service wix-bookings-rc-v2-backend.resources has a new message Image_3626650051 Service wix-bookings-rc-v2-backend.sessions operation createSession.examples[0] has changed body Service wix-bookings-rc-v2-backend message Image_3626650051 was removed
issues:
Operation eq has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (95))
Operation ne has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (135))
Operation eq has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (98))
Operation ne has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (138))
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_all.es6' not found. File: com_wix_bo ...