DocWorks for wix-bookings-rc-v2-backend - 12 changes detected, but 8 issue detected changes: Service wix-bookings-rc-v2-backend.sessions.BookingsRcV2QueryBuilder_68149959505 operation find has changed return type Service wix-bookings-rc-v2-backend.sessions.BookingsRcV2QueryResult_350238028899 was removed Service wix-bookings-rc-v2-backend.sessions operation createSession has changed return type Service wix-bookings-rc-v2-backend.sessions operation updateSession has changed param name from updateSessionOptions to options Service wix-bookings-rc-v2-backend.sessions operation updateSession has changed param options type Service wix-bookings-rc-v2-backend.sessions operation updateSession param options was removed Service wix-bookings-rc-v2-backend.sessions operation updateSession has changed return type Service wix-bookings-rc-v2-backend.sessions operation updateSession.examples[0] has changed body Service wix-bookings-rc-v2-backend.sessions message FieldMask_8457178585 was removed Service wix-bookings-rc-v2-backend.sessions has a new message FieldMask_7974751780 Service wix-bookings-rc-v2-backend has a new message Session_96580610885 Service wix-bookings-rc-v2-backend.sessions.BookingsRcV2QueryResult_191155255847 is new
issues:
Operation eq has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (90))
Operation ne has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (130))
Operation eq has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (28))
Operation ne has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (68))
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_all.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1241
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Boo ...