DocWorks for wix-bookings-rc-v2-backend - 12 changes detected, but 8 issue detected changes: Service wix-bookings-rc-v2-backend.resources operation createResource has changed param resourceInfo type Service wix-bookings-rc-v2-backend.resources operation createResource has changed return type Service wix-bookings-rc-v2-backend.resources operation createResource.examples[0] has changed body Service wix-bookings-rc-v2-backend.resources operation updateResource has changed param resource type Service wix-bookings-rc-v2-backend.resources operation updateResource has changed return type Service wix-bookings-rc-v2-backend.resources operation updateResource.examples[0] has changed body Service wix-bookings-rc-v2-backend.resources message Resource_8704016007 was removed Service wix-bookings-rc-v2-backend.resources message Resource_8796704728 was removed Service wix-bookings-rc-v2-backend.resources has a new message Resource_10583635105 Service wix-bookings-rc-v2-backend.resources has a new message Resource_10490946384 Service wix-bookings-rc-v2-backend message Resource_15083711512 was removed Service wix-bookings-rc-v2-backend has a new message Resource_16777953168
issues:
Operation eq has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (95))
Operation ne has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (135))
Operation eq has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (98))
Operation ne has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (138))
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_all.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1246
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_multiple_filters.es6' not found. File: co ...