DocWorks for wix-bookings-rc-v2-backend - 12 changes detected, but 8 issue detected changes: Service wix-bookings-rc-v2-backend.bookings.BookingsRcV2QueryBuilder_56496348945 operation find has changed return type Service wix-bookings-rc-v2-backend.bookings.BookingsRcV2QueryResult_323641466889 was removed Service wix-bookings-rc-v2-backend.bookings operation setAttendance has changed return type Service wix-bookings-rc-v2-backend.bookings operation setBookingAsPaid has changed return type Service wix-bookings-rc-v2-backend.bookings operation updateCustomerInfo has changed return type Service wix-bookings-rc-v2-backend.bookings message Booking_241733789927 was removed Service wix-bookings-rc-v2-backend.bookings has a new message Booking_226816542711 Service wix-bookings-rc-v2-backend message Booking_348148577543 was removed Service wix-bookings-rc-v2-backend message PaymentDetails_93427079082 was removed Service wix-bookings-rc-v2-backend has a new message Booking_333231330327 Service wix-bookings-rc-v2-backend has a new message PaymentDetails_78509831866 Service wix-bookings-rc-v2-backend.bookings.BookingsRcV2QueryResult_308724219673 is new
issues:
Operation eq has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (90))
Operation ne has an unknown param type * (com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js (130))
Operation eq has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (28))
Operation ne has an unknown param type * (com_wix_bookings_calendar_api_v1_CalendarService_ListSessions_querySessions.js (68))
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_all.es6' not found. File: com_wix_bookings_api_v1_BookingsReader_Query_queryBookings.js line: 1241
ERROR: The @snippet tag - file 'corvid-docs/examples/com_wix_bookings_api_v1_Bookings_queryBookings_multiple_filters.es6' not found. File: com_wix_bookings_api ...